export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'


// Business Types
export const SET_INITIAL_DATA = 'SET_INITIAL_DATA'
export const SET_INITIAL_DATA_FAILURE = 'SET_INITIAL_DATA_FAILURE'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_RESULTS_SUCCESS = 'SET_SEARCH_RESULTS_SUCCESS'
export const SET_SEARCH_RESULTS_FAILURE = 'SET_SEARCH_RESULTS_FAILURE'

export const SET_BUSINESS = 'SET_BUSINESS'
